### ISSUE TITLE
Plugin doesn't work with NodeBB 1.7.2

### ISSUE THREAD

**Issue by x1nf1** [pichalite/nodebb-plugin-assign-newuser-to-group#4]
Hello @barisusakli and @pichalite , unfortunately the plugin doesn't assign new users to a particular group in NodeBB 1.7.2

**Comment by barisusakli** [comment]
Maybe @pichalite didn't publish the latest version to npm? The code looks ok to me for 1.7.2

**Comment by x1nf1** [comment]
Hi @pichalite @barisusakli , Does it work for you in 1.7.5 ? 😄

**Comment by barisusakli** [comment]
@pichalite can you transfer this plugin to https://github.com/NodeBB-Community and give me publish rights?
